### ISSUE TITLE
Website Documentation. SUSE install instructions incorrect

### ISSUE THREAD

**Issue by simonc6372** [wslutilities/documentation#28]
### Windows Version

Windows 11

### Windows Build Number

n/a

### WSL Version

Not Applicable

### Distro Version

n/a

### WSL Utilities Version

n/a

### Describe the bug

Your website install page indicates to run `zypper up` after adding the repositories, but before installing wslu
`zypper up` installs all available updates, and is not directly analogous to `apt-get update` 

The correct command after adding repositories is 
`zypper ref` 

I couldn't figure out how to register on https://git.wedotstud.io/wslu/documentation so I can't prepare a PR to fix it. 

### Steps to Reproduce

n/a

### Expected behavior

n/a

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by car-meows** [comment]
You can submit fixes on GitHub here: https://github.com/wslutilities/documentation

**Comment by simonc6372** [comment]
https://github.com/wslutilities/documentation/pull/29
